### ISSUE TITLE
Struct layout

### ISSUE THREAD

**Issue by flauntingspade4** [ankokovin/RustSnitch#5]
In general in rust, structs don't contain a field like your `type_result`, any method that can fail will return a `Result<T, U>`/`Option<T>`

You can completely eliminate the `ProgramResult` struct, and your `ResultType`, replacing them with nothing, and a `Result<()>` respectively, without losing any flexibility of the program

**Comment by ankokovin** [comment]
Yes I just had same thoughts when I saw the `Result` type! Since I just started learning Rust, I just made the result struct based on my (although quite limited) experience in other languages. Thank you very much, will refactor this soon.
